apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
spec:
  revisionHistoryLimit: 0
  replicas: 4
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
        - name: main
          image: harbor.k8ssb.cpas.cz/ondrejsika/counter:2
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          startupProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 1
            failureThreshold: 30
          env:
            - name: REDIS
              value: redis
          envFrom:
            - configMapRef:
                name: counter
          resources:
            requests:
              cpu: 50m
              memory: 30Mi
            limits:
              cpu: 100m
              memory: 60Mi
